[
  // adds the backslash before greek letters
  { trigger: "([^\\\\])(${GREEK})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before Greek letters" },
  { trigger: "([^\\\\])(${SYMBOL})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before symbols" },

  { trigger: "@a", replacement: "α", options: "mA" },
  { trigger: "@b", replacement: "β", options: "mA" },
  { trigger: "@g", replacement: "γ", options: "mA" },
  { trigger: "@G", replacement: "Γ", options: "mA" },
  { trigger: "@d", replacement: "δ", options: "mA" },
  { trigger: "@D", replacement: "Δ", options: "mA" },
  { trigger: "@e", replacement: "ϵ", options: "mA" },
  { trigger: ":e", replacement: "\\varepsilon", options: "mA" },
  { trigger: "@z", replacement: "ζ", options: "mA" },
  { trigger: "@t", replacement: "θ", options: "mA" },
  { trigger: "@T", replacement: "Θ", options: "mA" },
  { trigger: ":t", replacement: "\\vartheta", options: "mA" },
  { trigger: "@i", replacement: "ι", options: "mA" },
  { trigger: "@k", replacement: "κ", options: "mA" },
  { trigger: "@l", replacement: "λ", options: "mA" },
  { trigger: "@L", replacement: "Λ", options: "mA" },
  { trigger: "@s", replacement: "σ", options: "mA" },
  { trigger: "@S", replacement: "Σ", options: "mA" },
  { trigger: "@u", replacement: "υ", options: "mA" },
  { trigger: "@U", replacement: "Υ", options: "mA" },
  { trigger: "@o", replacement: "ω", options: "mA" },
  { trigger: "@O", replacement: "Ω", options: "mA" },
  { trigger: "ome", replacement: "\\omega", options: "mA" },
  { trigger: "Ome", replacement: "\\Omega", options: "mA" },
  { trigger: "psi", replacement: "\\psi", options: "mA" },
]
